### ISSUE TITLE
Chapter 9: timerAudio.c

### ISSUE THREAD

**Issue by zenabis** [hexagon5un/AVR-Programming#15]
At the beginning of the playNote function, there should be a counter reset, I think. Otherwise some tones get skipped in my case. (It's more problematic for me, since I use an Atmega8 with the 16bit counter).

**Comment by hexagon5un** [comment]
Interesting problem.  I must have missed it b/c the 8-bit counter rolls around fast enough anyway.  

I added in a `TCCNT0=0;` which should do it. 

Thanks for the catch!
