### ISSUE TITLE
Wrong example

### ISSUE THREAD

**Issue by jstar88** [hexagon5un/AVR-Programming#22]
On this example:
https://github.com/hexagon5un/AVR-Programming/blob/master/Chapter02_Programming-AVRs/blinkLED/blinkLED.c

 DDRB |= 0b0000001;
should be
 DDRB |= 0b00000001;

**Comment by hexagon5un** [comment]
Fixed.  Thanks for pointing that out.  I have no idea how I missed that or how it lived for a few years...

**Comment by jstar88** [comment]
thank you for your great book

**Comment by hexagon5un** [comment]
@jstar88 You're more than welcome!  Yay!
