### ISSUE TITLE
Unused makefile definitions

### ISSUE THREAD

**Issue by sf1** [hexagon5un/AVR-Programming#7]
Hi, first of all thanks for this awesome resource. I just had a look at the chapter 2 makefile and I noticed  there are two variable definitions that are never used in any of the rules:

    ##List of all header files
    HEADERS = $(SRC:.c=.h) 

    ##For every .c file, compile an .o object file
    OBJ = $(SRC:.c=.o) 

Probably remnants from an earlier version?

**Comment by hexagon5un** [comment]
Heya,

I finally got around to re-writing (minor bits of) the Makefile, and it's much more "normal" now. 

All better.
